[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file_share = {path = "../file_share"}
bincode = "1.3.3"
serde = { version = "1.0.144", features = ["derive"]}
